### ISSUE TITLE
PostgreSQL schema incomplete

### ISSUE THREAD

**Issue by tdecoene** [wisemapping/wisemapping-open-source#1]
Hello,

The SQL schema creation for PostgreSQL is incomplete : the table `label` lacks the `iconname` column.

https://github.com/wisemapping/wisemapping-open-source/blob/d44c911bc1bbe30eb6937b59537c049ba0e7dff0/config/database/postgres/create-schemas.sql#L24

**Comment by veigap** [comment]
Thanks for the feedback. I'm merding a refactor that includes several improvements.
